site_name: PlagDetect

copyright: Copyright (c) 2023 Norbert Toth

theme:
    name: readthedocs
    highlightjs: true

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

nav:
  - PlagDetect: index.md
  - About PlagDetect:
    - Background: background.md
    - Training: Training.md
    - Inference: Inference.md
    - Textural Work: textural_work.md
    - How to cite: cite.md
    - How to contribute: contribute.md
  - Examples:
    - Training Example: examples/mmdetect-maskrcnn.ipynb
    - Example Inference: examples/example_inference.md
    - Skuggafjoll: examples/Skuggafjoll_analysis.ipynb
    - Sill Calibration: examples/Sill_calibration.ipynb
  - References:
    - Detector: references/detector.md
    - NMS: references/NMS.md
    - Tiling: references/tiling.md
    - Slicing: references/slicing.md
    - Thresholding: references/thresholding.md
    - Run: references/run.md
    - Process:
       - Measure: references/measure.md
       - Texture: references/texture.md
       - ShapeCalc: references/shape_calc.md
       - MCMC Prediction: references/mcmc.md
  - Licence: licence.md
